### ISSUE TITLE
unescaped characters

### ISSUE THREAD

**Issue by Apooolline** [CallMeKitsu/ShimiBot#8]
Les caractères spéciaux genre "𝔟𝔬𝔲𝔥" ça marche pas dans les giveaway, voilà

**Comment by Apooolline** [comment]
Ah et Kitsu est incroyable, beaucoup

**Comment by Apooolline** [comment]
Kitsu t'es incroyable

**Comment by CallMeKitsu** [comment]
// giveaway
// lol

**Comment by Apooolline** [comment]
𝔟𝔬𝔲𝔥

**Comment by Apooolline** [comment]
...

**Comment by Apooolline** [comment]
1. T'es incroyable
2. T'es trop incroyable
3. Kitsuuuuuu t'es incroyable
